made intakeCone also work for cubes
FRCTeam3255/2023_Offbot_Code pull request #11
Opened 2023-09-09 00:07 UTC by Alenguye582

included an if statement to make intake speed change depending on the game piece

2023-09-09 00:22 UTC, TaylerUva requested changes

2023-09-09 00:22 UTC, TaylerUva commented on src/main/java/frc/robot/RobotPreferences.java
> +    public static final SN_DoublePreference elevatorIntakingPos = new SN_DoublePreference("elevatorConeIntakingPos",
The variable name and key string do not match

2023-09-09 16:21 UTC, ACat701 submitted a review, later dismissed

2023-09-09 16:21 UTC, ACat701 commented on src/main/java/frc/robot/RobotContainer.java
> +    conOperator.btn_RightBumper.onTrue(new IntakeGamePiece(subWrist, subIntake, subElevator, GamePiece.CUBE));
// Intake Cube (LB)
you typed btn_RightBumper

2023-09-09 16:21 UTC, ACat701 commented on src/main/java/frc/robot/RobotPreferences.java
> +    public static final SN_DoublePreference elevatorIntakingPos = new SN_DoublePreference("elevatorIntakingPos",
Could you add a unit to this? If there is no unit you don't need to

2023-09-09 16:21 UTC, ACat701 commented on src/main/java/frc/robot/commands/IntakeGamePiece.java
> +    }
Could you add a fallback condition? I know it should never be anything else but redundancy doesn't hurt

2023-09-09 19:43 UTC, TaylerUva submitted a review, later dismissed

2023-09-15 23:46 UTC, TaylerUva approved these changes

2023-09-15 23:47 UTC, merged