created placeGamePiece command
FRCTeam3255/2023_Offbot_Code pull request #17
Opened 2023-09-16 02:00 UTC by Alenguye582

- created DesiredHeight enum
- made D-pad set the desired height
- made scoring height preferences

2023-09-16 18:56 UTC, TaylerUva requested changes

2023-09-16 18:56 UTC, TaylerUva commented on src/main/java/frc/robot/commands/PrepGamePiece.java
> +    }
This could be converted to a switch statement to make code easier

2023-09-19 04:01 UTC, EliUva approved these changes

2023-09-19 04:02 UTC, TaylerUva approved these changes

2023-09-19 19:24 UTC, merged